server:
  port: ${PORT:8084}

spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://oauth2-server:9000}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
